package CH.ifa.draw.test.util.collections.jdk12;

import junit.framework.TestCase;
// JUnitDoclet begin import
import CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12;
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


// JUnitDoclet begin javadoc_class
/**
* TestCase CollectionsFactoryJDK12Test is generated by
* JUnitDoclet to hold the tests for CollectionsFactoryJDK12.
* @see CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12
*/
// JUnitDoclet end javadoc_class
public class CollectionsFactoryJDK12Test
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // instance variables, helper methods, ... put them in this marker
  CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12 collectionsfactoryjdk12 = null;
  // JUnitDoclet end class
  
  /**
  * Constructor CollectionsFactoryJDK12Test is
  * basically calling the inherited constructor to
  * initiate the TestCase for use by the Framework.
  */
  public CollectionsFactoryJDK12Test(String name) {
    // JUnitDoclet begin method CollectionsFactoryJDK12Test
    super(name);
    // JUnitDoclet end method CollectionsFactoryJDK12Test
  }
  
  /**
  * Factory method for instances of the class to be tested.
  */
  public CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12 createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12();
    // JUnitDoclet end method testcase.createInstance
  }
  
  /**
  * Method setUp is overwriting the framework method to
  * prepare an instance of this TestCase for a single test.
  * It's called from the JUnit framework only.
  */
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    collectionsfactoryjdk12 = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  /**
  * Method tearDown is overwriting the framework method to
  * clean up after each single test of this TestCase.
  * It's called from the JUnit framework only.
  */
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    collectionsfactoryjdk12 = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  // JUnitDoclet begin javadoc_method createList()
  /**
  * Method testCreateList is testing createList
  * @see CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12#createList()
  */
  // JUnitDoclet end javadoc_method createList()
  public void testCreateList() throws Exception {
    // JUnitDoclet begin method createList
    // JUnitDoclet end method createList
  }
  
  // JUnitDoclet begin javadoc_method createMap()
  /**
  * Method testCreateMap is testing createMap
  * @see CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12#createMap()
  */
  // JUnitDoclet end javadoc_method createMap()
  public void testCreateMap() throws Exception {
    // JUnitDoclet begin method createMap
    // JUnitDoclet end method createMap
  }
  
  // JUnitDoclet begin javadoc_method createSet()
  /**
  * Method testCreateSet is testing createSet
  * @see CH.ifa.draw.util.collections.jdk12.CollectionsFactoryJDK12#createSet()
  */
  // JUnitDoclet end javadoc_method createSet()
  public void testCreateSet() throws Exception {
    // JUnitDoclet begin method createSet
    // JUnitDoclet end method createSet
  }
  
  
  
  // JUnitDoclet begin javadoc_method testVault
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * <b>Method testVault is supposed to be empty.</b>
  */
  // JUnitDoclet end javadoc_method testVault
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  /**
  * Method to execute the TestCase from command line
  * using JUnit's textui.TestRunner .
  */
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(CollectionsFactoryJDK12Test.class);
    // JUnitDoclet end method testcase.main
  }
}
