package CH.ifa.draw.test.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import CH.ifa.draw.util.ReverseListEnumerator;
import CH.ifa.draw.util.CollectionsFactory;

import java.util.List;
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


// JUnitDoclet begin javadoc_class
/**
* TestCase ReverseListEnumeratorTest is generated by
* JUnitDoclet to hold the tests for ReverseListEnumerator.
* @see CH.ifa.draw.util.ReverseListEnumerator
*/
// JUnitDoclet end javadoc_class
public class ReverseListEnumeratorTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // instance variables, helper methods, ... put them in this marker
  CH.ifa.draw.util.ReverseListEnumerator reverselistenumerator = null;
  // JUnitDoclet end class
  
  /**
  * Constructor ReverseListEnumeratorTest is
  * basically calling the inherited constructor to
  * initiate the TestCase for use by the Framework.
  */
  public ReverseListEnumeratorTest(String name) {
    // JUnitDoclet begin method ReverseListEnumeratorTest
    super(name);
    // JUnitDoclet end method ReverseListEnumeratorTest
  }
  
  /**
  * Factory method for instances of the class to be tested.
  */
  public CH.ifa.draw.util.ReverseListEnumerator createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
	List l = CollectionsFactory.current().createList();
	l.add("TestString1");
	l.add("TestString2");
    return new CH.ifa.draw.util.ReverseListEnumerator(l);
    // JUnitDoclet end method testcase.createInstance
  }
  
  /**
  * Method setUp is overwriting the framework method to
  * prepare an instance of this TestCase for a single test.
  * It's called from the JUnit framework only.
  */
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    reverselistenumerator = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  /**
  * Method tearDown is overwriting the framework method to
  * clean up after each single test of this TestCase.
  * It's called from the JUnit framework only.
  */
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    reverselistenumerator = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  // JUnitDoclet begin javadoc_method hasNext()
  /**
  * Method testHasNext is testing hasNext
  * @see CH.ifa.draw.util.ReverseListEnumerator#hasNext()
  */
  // JUnitDoclet end javadoc_method hasNext()
  public void testHasNext() throws Exception {
    // JUnitDoclet begin method hasNext
    // JUnitDoclet end method hasNext
  }
  
  // JUnitDoclet begin javadoc_method next()
  /**
  * Method testNext is testing next
  * @see CH.ifa.draw.util.ReverseListEnumerator#next()
  */
  // JUnitDoclet end javadoc_method next()
  public void testNext() throws Exception {
    // JUnitDoclet begin method next
    // JUnitDoclet end method next
  }
  
  // JUnitDoclet begin javadoc_method remove()
  /**
  * Method testRemove is testing remove
  * @see CH.ifa.draw.util.ReverseListEnumerator#remove()
  */
  // JUnitDoclet end javadoc_method remove()
  public void testRemove() throws Exception {
    // JUnitDoclet begin method remove
    // JUnitDoclet end method remove
  }
  
  
  
  // JUnitDoclet begin javadoc_method testVault
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * <b>Method testVault is supposed to be empty.</b>
  */
  // JUnitDoclet end javadoc_method testVault
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  /**
  * Method to execute the TestCase from command line
  * using JUnit's textui.TestRunner .
  */
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(ReverseListEnumeratorTest.class);
    // JUnitDoclet end method testcase.main
  }
}
