package CH.ifa.draw.test.util;

import junit.framework.TestCase;
// JUnitDoclet begin import
import CH.ifa.draw.util.GraphLayout;
// JUnitDoclet end import

/*
* Generated by JUnitDoclet, a tool provided by
* ObjectFab GmbH under LGPL.
* Please see www.junitdoclet.org, www.gnu.org
* and www.objectfab.de for informations about
* the tool, the licence and the authors.
*/


// JUnitDoclet begin javadoc_class
/**
* TestCase GraphLayoutTest is generated by
* JUnitDoclet to hold the tests for GraphLayout.
* @see CH.ifa.draw.util.GraphLayout
*/
// JUnitDoclet end javadoc_class
public class GraphLayoutTest
// JUnitDoclet begin extends_implements
extends TestCase
// JUnitDoclet end extends_implements
{
  // JUnitDoclet begin class
  // instance variables, helper methods, ... put them in this marker
  CH.ifa.draw.util.GraphLayout graphlayout = null;
  // JUnitDoclet end class
  
  /**
  * Constructor GraphLayoutTest is
  * basically calling the inherited constructor to
  * initiate the TestCase for use by the Framework.
  */
  public GraphLayoutTest(String name) {
    // JUnitDoclet begin method GraphLayoutTest
    super(name);
    // JUnitDoclet end method GraphLayoutTest
  }
  
  /**
  * Factory method for instances of the class to be tested.
  */
  public CH.ifa.draw.util.GraphLayout createInstance() throws Exception {
    // JUnitDoclet begin method testcase.createInstance
    return new CH.ifa.draw.util.GraphLayout();
    // JUnitDoclet end method testcase.createInstance
  }
  
  /**
  * Method setUp is overwriting the framework method to
  * prepare an instance of this TestCase for a single test.
  * It's called from the JUnit framework only.
  */
  protected void setUp() throws Exception {
    // JUnitDoclet begin method testcase.setUp
    super.setUp();
    graphlayout = createInstance();
    // JUnitDoclet end method testcase.setUp
  }
  
  /**
  * Method tearDown is overwriting the framework method to
  * clean up after each single test of this TestCase.
  * It's called from the JUnit framework only.
  */
  protected void tearDown() throws Exception {
    // JUnitDoclet begin method testcase.tearDown
    graphlayout = null;
    super.tearDown();
    // JUnitDoclet end method testcase.tearDown
  }
  
  // JUnitDoclet begin javadoc_method addNode()
  /**
  * Method testAddNode is testing addNode
  * @see CH.ifa.draw.util.GraphLayout#addNode(CH.ifa.draw.framework.Figure)
  */
  // JUnitDoclet end javadoc_method addNode()
  public void testAddNode() throws Exception {
    // JUnitDoclet begin method addNode
    // JUnitDoclet end method addNode
  }
  
  // JUnitDoclet begin javadoc_method addEdge()
  /**
  * Method testAddEdge is testing addEdge
  * @see CH.ifa.draw.util.GraphLayout#addEdge(CH.ifa.draw.framework.ConnectionFigure, int)
  */
  // JUnitDoclet end javadoc_method addEdge()
  public void testAddEdge() throws Exception {
    // JUnitDoclet begin method addEdge
    // JUnitDoclet end method addEdge
  }
  
  // JUnitDoclet begin javadoc_method relax()
  /**
  * Method testRelax is testing relax
  * @see CH.ifa.draw.util.GraphLayout#relax()
  */
  // JUnitDoclet end javadoc_method relax()
  public void testRelax() throws Exception {
    // JUnitDoclet begin method relax
    // JUnitDoclet end method relax
  }
  
  // JUnitDoclet begin javadoc_method figureChanged()
  /**
  * Method testFigureChanged is testing figureChanged
  * @see CH.ifa.draw.util.GraphLayout#figureChanged(CH.ifa.draw.framework.FigureChangeEvent)
  */
  // JUnitDoclet end javadoc_method figureChanged()
  public void testFigureChanged() throws Exception {
    // JUnitDoclet begin method figureChanged
    // JUnitDoclet end method figureChanged
  }
  
  // JUnitDoclet begin javadoc_method remove()
  /**
  * Method testRemove is testing remove
  * @see CH.ifa.draw.util.GraphLayout#remove()
  */
  // JUnitDoclet end javadoc_method remove()
  public void testRemove() throws Exception {
    // JUnitDoclet begin method remove
    // JUnitDoclet end method remove
  }
  
  
  
  // JUnitDoclet begin javadoc_method testVault
  /**
  * JUnitDoclet moves marker to this method, if there is not match
  * for them in the regenerated code and if the marker is not empty.
  * This way, no test gets lost when regenerating after renaming.
  * <b>Method testVault is supposed to be empty.</b>
  */
  // JUnitDoclet end javadoc_method testVault
  public void testVault() throws Exception {
    // JUnitDoclet begin method testcase.testVault
    // JUnitDoclet end method testcase.testVault
  }
  
  /**
  * Method to execute the TestCase from command line
  * using JUnit's textui.TestRunner .
  */
  public static void main(String[] args) {
    // JUnitDoclet begin method testcase.main
    junit.textui.TestRunner.run(GraphLayoutTest.class);
    // JUnitDoclet end method testcase.main
  }
}
