/*
 * ODGProject.java
 *
 * Created on January 15, 2007, 7:59 PM
 */

package org.jhotdraw.samples.odg;

import java.io.File;
import java.io.IOException;
import org.jhotdraw.app.AbstractProject;

/**
 *
 * @author  werni
 */
public class ODGProject extends AbstractProject {
    
    /** Creates new form ODGProject */
    public ODGProject() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void write(File f) throws IOException {
    }

    public void read(File f) throws IOException {
    }

    public void clear() {
    }
    
}
