/*
 * @(#)JColorSquare.java
 * 
 * Copyright (c) 2010 by the original authors of JHotDraw
 * and all its contributors.
 * All rights reserved.
 * 
 * The copyright of this software is owned by the authors and  
 * contributors of the JHotDraw project ("the copyright holders").  
 * You may not use, copy or modify this software, except in  
 * accordance with the license agreement you entered into with  
 * the copyright holders. For details see accompanying license terms. 
 */

package org.jhotdraw.color;

/**
 * JColorSquare.
 *
 * @author Werner Randelshofer
 * @version 1.0 2010-01-20 Created.
 */
public class JColorSquare extends JColorWheel {

    /** Creates new form JColorSquare */
    public JColorSquare() {
        initComponents();
    }

    @Override
    protected AbstractColorWheelImageProducer createWheelProducer(int w, int h) {
        AbstractColorWheelImageProducer p = new ColorSquareImageProducer(model.getColorSystem(), w, h);
        p.setAngularComponentIndex(angularIndex);
        p.setRadialComponentIndex(radialIndex);
        p.setVerticalComponentIndex(verticalIndex);
        return p;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
